name: deploy pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: build, tag and push to ECR
        env: 
          ECR_REGISTRY: 288761764400.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPO: test-ecr
        run: |
          IMAGE_TAG=github-api-latest
          echo "Building docker image"
          IMAGE_URI= ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}
          docker build --platform=linux/amd64 -t ${IMAGE_URI} .
          docker push ${IMAGE_URI}


